### ISSUE TITLE
NULLSTACK_SERVER_PORT being ignored

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#116]
NULLSTACK_SERVER_PORT is not working, however yarn start -p 3000 works

**Comment by ManishBansiwal29** [comment]
I would like to work on this please.

**Comment by Mortaro** [comment]
Awesome @ManishBansiwal29 

few tips from a quick debug session:

- The file scripts\index.js needs to conditionally check if we have a port before assigning the value to the env variable
- The commander should not have a default value assigned to the option as that is overriding the server default

**Comment by ManishBansiwal29** [comment]
hey @Mortaro I have made some changes.
Can you let me know how do i test them?

**Comment by Mortaro** [comment]
You can set the port on tests .env to use 6969 and if it does not break the tests its working, you can also use a test similar to the scripts test to run with yarn npx nullstack start -p 5000 and watch the console for the output containing :5000 to test the command line case

**Comment by Mortaro** [comment]
@ManishBansiwal29 heyo, i'll spend the weekend doing some open issues. Ill be available to pair this weekend if you need help on this one! (o゜▽゜)o☆

**Comment by ManishBansiwal29** [comment]
hey @Mortaro, I'm sorry for the inactivity. I'm currently in the middle of university exams and I would not be able to put my efforts on the issue this weekend.
