### ISSUE TITLE
Change default port to ????

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#133]
Nullstack is crashing in some macbooks because port 5000 is taken, should we move to port 3000 like normies or do something else?

ಥ_ಥ i liked 5000

**Comment by Mortaro** [comment]
Nullstack should not have a default port on its sourcecode, it should read from NULLSTACK_SERVER_PORT or PORT, if its not in server.less mode and does not have a defined port it should stop execution with an error in the console (should be red)
The port should be changed to (possibly) 3000 at create-nullstack-app repo

useful references:

https://github.com/nullstack/nullstack/blob/49ddf433496072f6291f36844d91299dfd7b3f4e/server/server.js#L28
https://github.com/nullstack/nullstack/blob/49ddf433496072f6291f36844d91299dfd7b3f4e/scripts/index.js#L33
https://github.com/nullstack/create-nullstack-app/blob/master/src/template/README.md
https://github.com/nullstack/create-nullstack-app/blob/master/src/template/_env

**Comment by MarceloBorgesP** [comment]
Let me work on that!

**Comment by MarceloBorgesP** [comment]
@Mortaro check if this is what we need pls!

**Comment by Mortaro** [comment]
merged into #next thanks @MarceloBorgesP!
