### ISSUE TITLE
Fix purge pattern

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#145]
Update the purge pattern for tailwind new format using . and []

**Comment by edysegura** [comment]
I'm on it!!

**Comment by edysegura** [comment]
It seems they don't have a fat css file for this version like they do for the previous version!

![image](https://user-images.githubusercontent.com/5324414/148474274-3fc06eef-5b51-4484-9383-7e7ddefde34e.png)

As that said still this issue valid?

**Comment by Mortaro** [comment]
@edysegura  Purge is not only for tailwind, so the process will always happen, we still need this to avoid removing classes from TW that should not be removed because they had a dot or brackets in it

**Comment by Mortaro** [comment]
beautifully done, thanks @edysegura (o゜▽゜)o☆
