### ISSUE TITLE
Run Nullstack tests on GitHub Actions

### ISSUE THREAD

**Issue by edysegura** [nullstack/nullstack#152]
![image](https://user-images.githubusercontent.com/5324414/149438730-a39f6884-f6c9-46a0-8e47-468c316c0f56.png)

**Comment by Mortaro** [comment]
This would be awesome, wanna go for it? (o゜▽゜)o☆

**Comment by GuiDevloper** [comment]
I've been testing and diving on this very interesting issue, then found myself working hard on this and already almost coming with full results :sweat_smile:

**Comment by Mortaro** [comment]
merged into #next (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
