### ISSUE TITLE
Body Fragment

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#17]
Replace the main tag at the application root with the body tag

The body tag will be a fragment alias but will reflect the attributes in the DOM body allowing the programmer to control the body directly.

However, the application code will still be inside the "#application" div but this time without the main root

**Comment by GuiDevloper** [comment]
Hey, @Mortaro, hope everything is fine!

Been reading through these and would like to know what's the big deal about this one.
Wrote like this in `master`'s `Application.njs`:

```jsx
<body
  class={true ? "my-app" : "none"}
  style={false ? "background: red;" : ''}
>
  <h1> {project.name} </h1>
```

These attributes bind to DOM body, and even the content (`h1`) go below `div#application`.
This body's control is what this expects? Am I losing something there?

**Comment by Mortaro** [comment]
The idea is basically that. Nullstack application lives in a <div id="application"> currently the user has no access to the body.
 The application boilerplate is generated with a <main> tag as root, but I wanna leave that decision to the user.

To solve both problems a <body> tag should be used, but that would not create a second body inside #application, but instead become a parentless fragment inside the div, and the attributes in the body tag should be attached reactively in the real body both in client and server times

**Comment by Mortaro** [comment]
done in extremely-unstable-next (⌐■_■)
