### ISSUE TITLE
onClick not being set at times causes weird behavior on forms

### ISSUE THREAD

**Issue by joojscript** [nullstack/nullstack#174]
onClick not being set at times causes weird behavior on forms. Not only on forms, but actually on any point in the template that need that specific callback (for instance, a component which expects that not to be undefined).

The error seems to be as it shows:

![image](https://user-images.githubusercontent.com/49156424/154947360-6355b4c4-4bd5-4be5-98a3-f7a94db911a6.png)

Sometimes, based on things like the build proccess, or even the view you're rendering, the variable names could change, but the error is basically the same:

![image](https://user-images.githubusercontent.com/49156424/154947440-3ddf3842-69c8-4a4b-85ca-b4d5b8ac3973.png)

```javascript
import Nullstack from 'nullstack';

class Home extends Nullstack {

  visible = true

  render() {
    return (
      <section>
        <button onclick={{ visible: !this.visible }}> Toggle </button>
        {this.visible && <button onclick={undefined}> button </button>}
      </section>
    )
  }

}

export default Home;
```

**Comment by Mortaro** [comment]
Thanks for reporting! Fixed on 0.14 (o゜▽゜)o☆
