### ISSUE TITLE
Context Instances

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#18]
Refactor the scope into a class for the client and one for the server exposing the instance key to the context.

The application should be able to call a component by key and access its public methods like:

```
prepare({instances})  {
   instances.counter.count++;
}
```

This should add a new layer of freedom for plugin makers

**Comment by GuiDevloper** [comment]
Hey, for formalities, you can assign me this one too :grin:

**Comment by Mortaro** [comment]
This will be merged soon, Thanks 💖
