### ISSUE TITLE
Element Plugins

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#19]
Users should be able to create plugins that transform attributes of elements similar to the "route" and "bind" attributes which would allow creating things like VUE "if" directive

The plugin should respond to constructor/match/transform and receive an object with the scope, node, and depth keys.

Refer to https://github.com/nullstack/nullstack/tree/master/plugins for better examples

The API is still not decided but should be something in the likes of adding a Nullstack.use(Plugin) in the index.js

**Comment by GuiDevloper** [comment]
Hey brother, you can even assign me.
I'am on this :smirk: :rocket:

**Comment by Mortaro** [comment]
This will be merged soon, Thanks 💖
