### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#20]
Add support to type script on .nts files

**Comment by domuserk** [comment]
I can help you

**Comment by Mortaro** [comment]
Yay! please let me know on discord if you need any guidance on this task. We can make a call and i can give you a few pointers about where i left this task (its halfway done o/)

**Comment by domuserk** [comment]
RyanLopes#5092

**Comment by AdsonCicilioti** [comment]
🥲

**Comment by GuiDevloper** [comment]
Hey people!

I was thinking in something to improve Nullstack projects development and it's syntax versatility.
Then, between some experiences, used 2/3 nights giving life to an simple idea of converting TSX files into NJS without changing the framework and avoiding some weight a TS compiler would bring to my environment.

So, yep, I crossed with a curious solution for this issue of yours, lazily not creating a NTS file type.
I named it: https://github.com/GuiDevloper/nullstack-to-njs
As shown there, this is a working example: https://github.com/GuiDevloper/nullstack-tsx-example

**Comment by Mortaro** [comment]
WIP https://github.com/nullstack/nullstack/tree/typescript

**Comment by AdsonCicilioti** [comment]
It's awesome! 🥲

Sorry for i can't help more on this moment. 

Nice work guys! 🤲🏻

**Comment by Mortaro** [comment]
Done in next now we can use .nts files, will release soon!

Here is an example https://github.com/Mortaro/nullstack-simple-todo-typescript
