### ISSUE TITLE
Docker support 

### ISSUE THREAD

**Issue by robGetsTheJobDoneAE** [nullstack/nullstack#255]
### Request - Docker

As a developer, I often have to deploy applications to clients internal hosted clouds, generally a DevOps person will expect some form of a containerized app. 

**It would be fantastic if Nullstack auto-generated a Dockerfile**.

Also if one could override environment variables at container runtime([example](https://www.npmjs.com/package/runtime-env-cra)). it would be huge. 

**This would speed up developer + ops integration and save so much time compared to a classic react + express docker setup.**

**Comment by victorfernandesraton** [comment]
So, it's a simple nodejs runner project, you also create a docker-compose and we don't need an . Dockerfile by default, because it's simple,

**Comment by Mortaro** [comment]
Thanks for the suggestion! This will probably be part of deploy-nullstack-app
