### ISSUE TITLE
Refactor rerender

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack#27]
Refactor the node lookup inside rerender to instead pass the next nodes as parameters to the function

There is a comment indicating the lines in https://github.com/nullstack/nullstack/blob/master/client/rerender.js

**Comment by GuiDevloper** [comment]
Already coded this one in [nullstack/refactor-rerender](https://github.com/GuiDevloper/nullstack/tree/refactor-rerender)

Needs some insight if the issue was fully fixed, though.

**Comment by Mortaro** [comment]
Merged into master 💖
