### ISSUE TITLE
M1 Mac issue with node v16 fiber

### ISSUE THREAD

**Issue by EgonStep** [nullstack/nullstack#284]
When trying to start a project, I received the error bellow:

`Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file coroutine.cc, line 134.
zsh: abort      npm start`

pagacke.json

`{
  "name": "project",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "nullstack": "~0.16.5",
    "sass-loader": "^13.1.0"
  },
  "scripts": {
    "start": "npx nullstack start",
    "start-emulator": "flow emulator start",
    "deploy-contracts": "flow project deploy -n emulator --update",
    "build": "npx nullstack build"
  },
  "dependencies": {
    "@babel/core": "^7.19.3",
    "@babel/preset-env": "^7.19.4",
    "@onflow/fcl": "^1.3.1",
    "axios": "^1.1.3",
    "body-parser": "^1.20.1",
    "cadence-webpack-plugin": "^1.0.1",
    "cookie-session": "^2.0.0",
    "crypto": "^1.0.1",
    "sass": "^1.51.0"
  }
}
`

Issue resolved when downgrading node to version 14

**Comment by acneidert** [comment]
Hi! 

please, add this code in your ```webpack.config.js```, just for test...

```js
const [server, client] = require('nullstack/webpack.config');

function customClient(...args) {
  const config = client(...args);
  const rule = config.module.rules.find((rule) => rule.test.test('.css'));
  const sassLoader = rule.use.find((use) => {
    if (typeof use === 'object') {
      return use.loader.includes('sass-loader');
    }
    return false
  })
  sassLoader.options = {
    sassOptions: {
      fiber: false,
    },
  }
  return config;
}

module.exports = [server, customClient]
```

**Comment by EgonStep** [comment]
Hey Andre, here`s the error that I got

`ERROR in ./cadence/transactions/CreateCarbonCredit.cdc 1:29
Module parse failed: Identifier directly after number (1:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import CarbonCredit from 0xCarbonCreditAddress
| 
| transaction(description: String, credits: UInt64, patrimonyRegisterNumber: String) {
 @ ./src/flow/transactions.js 3:0-85 21:17-37
 @ ./src/Home.jsx 17:0-63 40:31-40 41:12-25
 @ ./src/Application.jsx 16:0-26 65:44-48
 @ ./client.js 2:0-44 7:32-43 61:45-63:7 62:28-39 61:6-63:8

webpack compiled with 1 error`

**Comment by EgonStep** [comment]
This worked 

`const [server, client] = require('nullstack/webpack.config');
const { applyCadencePlugin } = require('cadence-webpack-plugin')

function customClient(...args) {
  const config = client(...args);
  const rule = config.module.rules.find((rule) => rule.test.test('.css'));
  const sassLoader = rule.use.find((use) => {
    if (typeof use === 'object') {
      return use.loader.includes('sass-loader');
    }
    return false
  })
  sassLoader.options = {
    sassOptions: {
      fiber: false,
    },
  }
  return config;
}

module.exports = applyCadencePlugin([server, customClient])`

**Comment by Mortaro** [comment]
Thanks! this is now the default setting
