### ISSUE TITLE
Support urls with/without trailing slashes in Nullstatic

### ISSUE THREAD

**Issue by GuiDevloper** [nullstack/nullstack#30]
Examples:
Accessing [nullstack.app/contributors](https://nullstack.app/contributors) in Github Pages
Should work equal than accessing [nullstack.app/contributors/](https://nullstack.app/contributors/)

Targets those issues registered on Github Pages side:
https://github.com/jekyll/jekyll/issues/4440
https://stackoverflow.com/questions/33270605/github-pages-trailing-slashes
https://marcgg.com/blog/2016/03/14/github-pages-jekyll/

**Comment by Mortaro** [comment]
This seems to be an issue with the way Github deals with trailing slashes.

I solved this by generating both versions of the file, for example: contributors.html and contributors/index.html

https://github.com/nullstack/create-nullstatic-app/commit/eee4ea428a93f2298f0751e97ce2d154fc4fa0be

This solution should allow the programmer to not even think about structure while not having additional weight for the visitors.

By default Nullstack removes trailing slashes from router.path and rel canonical so this update should work greatly!
