### ISSUE TITLE
textarea attribute "disabled" won't update it's value when tied to nullstack state

### ISSUE THREAD

**Issue by Stefuu** [nullstack/nullstack#304]
## Description of the issue
For some reason the textarea "disabled" attribute won't update it's value when tied to nullstack state when that state changes, but it will respect the initial value of the state, it just doesn't work when changing the state

## To reproduce the issue
Run the [project](https://github.com/Stefuu/nullstack-textarea-issue ) normally 
$ npm i
$ npm run start
You will see that the input tag state is updated normally, but the same logic when applied to a textarea won't work, and if you manually change the initial state at the [home file](https://github.com/Stefuu/nullstack-textarea-issue/blob/main/src/Home.jsx), you will see that it respect the initial value, just not the changes to it

## Repo
https://github.com/Stefuu/nullstack-textarea-issue

**Comment by Mortaro** [comment]
Fixed in 0.17.3 💜
