### ISSUE TITLE
Textarea doesn't accept bind as undefined

### ISSUE THREAD

**Issue by fccoelho7** [nullstack/nullstack#314]
I noticed that textarea element does not accept binding as `undefined` like other form elements. I got the error below:

![image](https://user-images.githubusercontent.com/4829072/215614148-ee06b9ed-cbc9-40b3-b4e7-d616ca765bf7.png)

## replicating

```jsx
class Preview extends Nullstack {
  render() {
    <input bind={this.foo} />
    <textarea bind={this.bar} />
  }
}

```

the input element works, but the textarea does not.

**Comment by victorfernandesraton** [comment]
if you try define default value as a null or empty string? textarea es more diferent to other input elemtns because accepts children elements

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

so textarea don't have `value` or `defaultValue ` prpprety

**Comment by Mortaro** [comment]
This is now supported behavior 💜
