### ISSUE TITLE
Description header not be apply

### ISSUE THREAD

**Issue by victorfernandesraton** [nullstack/nullstack#323]
When apply `page.description` on `hydrate` or even `prepare`, it's not generated description meta tag

version: `0.17.2`

**Comment by Mortaro** [comment]
Heyo, can you confirm to me that you are on spa mode pls? On dev it skips applying seo tags during spa mode, i will add some documentation for that

**Comment by victorfernandesraton** [comment]
I this scenario i test on ssr mode

**Comment by Mortaro** [comment]
Heyo, the default behavior used to be to do these mutations only in SSR, but now it's enabled in SPA in both prod and dev modes. Thanks for helping improve the DX of Nullstack @victorfernandesraton !  💜

**Comment by Stefuu** [comment]
Will changes made to page context in the prepare method be on the initial HTML served on SPA mode? From docs i understand that prepare runs before the initial HTML is served, even for SPA

**Comment by Mortaro** [comment]
@Stefuu Prepare runs on server on first load of SSR and then on client after that for the new components, in both cases it will reflect metatags
