### ISSUE TITLE
.env variables not be referenced as a value

### ISSUE THREAD

**Issue by victorfernandesraton** [nullstack/nullstack#326]
I trying put one variable inside another for consume in server side functions
I started with .env files put this
````.env
FOO=bar
NULLSTACK_SECRETS_FOO=$FOO
````
For testing i set my source for this .env file

`source .env`

when a try usingn echo for NULLSTACK_SERCRETS_FOO i recive `bar` string, but when using context.secretes.foo i got `$FOO` insteread `bar` value

**Comment by Mortaro** [comment]
Sorry for the delay @victorfernandesraton , i've been using my maker time on the new compiler and forgot to answer here.

This behaviour is not something that comes out of the box with dotenv, but it would be super cool to have on nullstack by default. 

They recommend using: https://github.com/motdotla/dotenv-expand. 

PRs are welcome in case you want to add this behavior, you can use the branch "next" and there i have a few places i init dotenv depending on build mode

**Comment by victorfernandesraton** [comment]
Ok, i do not have time to implement but I will see how to do this, and if i could, maybe contribute with the project
