### ISSUE TITLE
Comments not being respected by sass-loader

### ISSUE THREAD

**Issue by robgetTheJobDoneSP** [nullstack/nullstack#359]
The following code breaks the sass-loader, the //bg-[path/to/your/image.jpg] is not being treated as a comment. 

`import Nullstack from 'nullstack'

class FunFact extends Nullstack {
  data = {}

  render() {
    // bg-[path/to/your/image.jpg]
    return <div></div>
  }
}
`

Some deps related to issue. 
`
    "nullstack": "^0.16.4",
     "eslint": "^8.20.0",
    "eslint-plugin-nullstack": "^0.0.26",
     "postcss": "^8.4.19",
    "postcss-loader": "^7.0.1",
     "tailwind-merge": "^1.4.0",
    "tailwindcss": "^3.2.4"
`

**Comment by Mortaro** [comment]
Thanks for reporting @robgetTheJobDoneSP  💜 Can you check if it still happens on 0.19.3, please? I'm unable to reproduce it on recent versions. Also, the new HMR on the latest versions might speed up your daily workflow by a lot!
