### ISSUE TITLE
Fix conflict with invokerHash and boundHash separator

### ISSUE THREAD

**Issue by HallexCosta** [nullstack/nullstack#375]
### Overview

Identified bug with `invokerHash` and `boundHash` hyphen `-` separator.

testing with file `favorites.tsx` (work)
![image](https://github.com/nullstack/nullstack/assets/55293671/619ea1df-4441-4a50-990d-b5d44baafaed)

testing with file `favorites-hallex.tsx` (don't work)
![image](https://github.com/nullstack/nullstack/assets/55293671/5beb4cc5-1311-43a2-b90f-312fee4603a9)

> The same problem occurred with folders created with names containing hyphen `-` like `src/design-system/foo/bar`

**Comment by Mortaro** [comment]
Thanks for the PR fixing it 💜
