### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ghost** [nullstack/nullstack#386]
Why when I changed cct in chrome, I get text messages? I'm not receiving all my text messages, and I Kno it's chrome setup that's preventing them from showing on my device. Please help me Why does my device show null?

**Comment by ghost** [comment]
IP: 172.56.65.199
Speed: 0 Mbps
Frequency: 0 MHz
Connection type: MOBILE
Internal IP: 2607:fb90:e3d9:1d0:8c89:7887:53be:54ab
Mac address: null
Signal: 0%
172.56.65.199
United States
GA
Atlanta
Latitude: 33.7485
Longitude: -84.3871
SSID: <unknown ssid>
BSSID: 02:00:00:00:00:00
Lease duration: 0
Server address: 0.0.0.0
Broadcast address: 0.0.0.0
DNS(1) address: 0.0.0.0
DNS(2) address: 0.0.0.0
Mask: 255.255.255.0
Gateway: 0.0.0.0
Localhost: 127.0.0.1
Subtype: LTE
Network ID:

**Comment by ghost** [comment]
Where do I get ssid

**Comment by alepdias** [comment]
É possível desenvolver uma plataforma SaaS de Troca de Tráfego com o Nullstack?
