### ISSUE TITLE
How do I write tests for a Nullstack application?

### ISSUE THREAD

**Issue by nelsonthedev** [nullstack/nullstack#390]
Any recommendations on how to write unit/component tests for a Nullstack application that can run fast and in isolation from outer services? I could not find anything related in the docs.
Thanks!

**Comment by Mortaro** [comment]
Hi, sorry for the delay, you can call any nullstack component methods normally, by simply instantiating the component without calling render, or you can also look into "[script runners"](https://nullstack.app/script-runner) that are able to run a NS application with its full context outside the web
