### ISSUE TITLE
Refresh a page on firefox causes it to refresh many times

### ISSUE THREAD

**Issue by WilliamCSA04** [nullstack/nullstack#67]
Whenever I try to refresh a page, it causes Firefox to reload infinity times, but this only happens on firefox. I have tried on Microsoft Edge and Google Chrome and on both it works just fine.

![Console bug firefox](https://user-images.githubusercontent.com/12972870/115642557-907f1e00-a2f1-11eb-8c64-924ff3b31a15.gif)
![Socket bug firefox](https://user-images.githubusercontent.com/12972870/115642585-a096fd80-a2f1-11eb-9ee3-f91145f4562c.gif)

**Comment by GuiDevloper** [comment]
Hey, @WilliamCSA04!

We tried to reproduce this issue here, but no success.
We gently ask for the code of an minimum example focused in the case where the bug happens, it would be of essential help!

Good full-stacking there :)

**Comment by WilliamCSA04** [comment]
@GuiDevloper hello!

I have tried to create a project with this same error, but I believe that these bugs only happen on bigger projects, because before that did not happened. I have showed that to @Mortaro so he has access to the code base that we are using.

**Comment by WilliamCSA04** [comment]
I have created a new project to test Firefox hot reload and seems that is working just fine on [next](https://github.com/nullstack/nullstack/tree/next). Even tho there was an error message the page successfully reloaded.
```
{
  "name": "firefox-bug",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "nullstack": "github:nullstack/nullstack#next"
  },
  "scripts": {
    "start": "npx nullstack start",
    "build": "npx nullstack build --mode=ssr"
  }
}
```

![Console showing live reload error but it was working](https://user-images.githubusercontent.com/12972870/152705073-b5d89bdb-f9e3-4afa-8165-4fc53ad93fd8.png)
