### ISSUE TITLE
Error when installing node-sass dependency

### ISSUE THREAD

**Issue by MaxHariel** [nullstack/nullstack#68]
I got some errors in the node-sass dependency install. This error happens on node 15.14.0 but works well with the LTS version(14.16.1)

![npmerror](https://user-images.githubusercontent.com/31599919/115773979-5eb89680-a387-11eb-90e7-3dd61eb44f79.png)

**Comment by Mortaro** [comment]
This error has been fixed. We moved from `node-sass` to `sass`. 

Please reopen if you have the same issue again 💜
