### ISSUE TITLE
It is not possible to conditionally render a SVG using ternaries.

### ISSUE THREAD

**Issue by WilliamCSA04** [nullstack/nullstack#70]
Problem: I was trying to change an SVG of a star from stroke to filled when the user clicked on it, but even after the component rerenders, the SVG did not change.

[I have created a repo with this bug](https://github.com/WilliamCSA04/bug-svg-ternary) for testing purposes. [This is the ternary line on my code](https://github.com/WilliamCSA04/bug-svg-ternary/blob/1e9a50a032d06925cccf5032f235a244f6bf43b6/src/Home.njs#L48).

I also have added a gif to illustrate it. First I show that the normal ternary is working by hiding and showing Nulla-Chan. However, when I try to change the star icon by clicking it, nothing happens.

![Nullstack bug](https://user-images.githubusercontent.com/12972870/116014480-e1ea1e80-a60b-11eb-9104-1a0264c579a8.gif)

**Comment by Mortaro** [comment]
This is the best bug report ever. 💜
