### ISSUE TITLE
When I try to create a nullstack app in the current folder, it doesn't work.

### ISSUE THREAD

**Issue by PatoGordo** [nullstack/nullstack#84]
![create-nullstack-app error](https://user-images.githubusercontent.com/59514690/121784165-d2f20800-cb88-11eb-8a45-7001e2482a49.png)

**Comment by domuserk** [comment]
@PatoGordo  (npx create-nullstack-app nome do app), acho que essa seria a sintaxe correta para criar.

**Comment by domuserk** [comment]
@Mortaro resolvido.
