### ISSUE TITLE
Commands not working when package is linked

### ISSUE THREAD

**Issue by GuiDevloper** [nullstack/nullstack#85]
After linking the nullstack package and running one of it's commands,
it searches for current folder going directories above, but being linked it is always wrong

Steps to reproduce:
- link this package to a new Nullstack project
- run one of: `npm run start`/`npm run build` there
- shows error of directory not found (looking levels above the real, following fixed path)

**Comment by Mortaro** [comment]
Resolvido pelo nosso lendario /o/
