### ISSUE TITLE
Problema com XSS

### ISSUE THREAD

**Issue by acneidert** [nullstack/nullstack#87]
Em meus testes encontrei um problema com XSS
https://github.com/acneidert/null_xss

Basicamente ele está renderizando tags <script> no body

O que imagino de possível solução: 
Converter  caracteres especiais como ?, &, /, <,> E espaços para códigos HTML. 

![image](https://user-images.githubusercontent.com/10155152/122767894-7b832480-d279-11eb-9628-f84055fff2fa.png)

**Comment by Mortaro** [comment]
Esqueci de marcar como resolvido. Valeu! (o゜▽゜)o☆
