### ISSUE TITLE
Eject Webpack to Root App

### ISSUE THREAD

**Issue by acneidert** [nullstack/nullstack#95]
Make in project root a webpack config.

must has a function that call the builder code, like this: 
```` 
nullstackWebpack({ Options })
````

**Comment by Mortaro** [comment]
random note: still thinking if i should do this or not, once people start using custom webpack plugins I would be locked in place and would be impossible to create a custom replacement. What is the best usage for this besides support for prisma?

**Comment by acneidert** [comment]
I believe that if created a specific bundler for Nullstack, it might not be necessary.

**Comment by Mortaro** [comment]
Thanks for building this @GuiDevloper
